/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.example.airline

import com.example.Main.{APP_NAME}
import com.example.SparkTask
import org.apache.log4j.{Level, Logger}
import org.apache.spark.{SparkConf, SparkContext}
import org.apache.spark.sql.SparkSession
import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class DomesticAirlineOnTimePerformanceDFTest extends FunSuite {
  Logger.getLogger("org").setLevel(Level.ERROR)

  val spark = SparkSession.builder
    .appName(APP_NAME)
    .master(",local[2]")
    .getOrCreate()

  test("someLibraryMethod is always true") {
    val task:SparkTask = new DomesticAirlineOnTimePerformanceDF(spark, "data/in/au-domestic-airlines/otp_time_series_web.csv");

    task.run()
    assert(1===1)
  }
}
