/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.example.airline

import com.example.Main.{AIRLINE_CSV_FILE, APP_NAME, MASTER}
import com.example.SparkTask
import org.apache.log4j.{Level, Logger}
import org.apache.spark.{SparkConf, SparkContext}
import org.apache.spark.sql.SparkSession
import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class DomesticAirlineOnTimePerformanceDFTest extends FunSuite {
  test("someLibraryMethod is always true") {
//    def library = new Library()
//    assert(library.someLibraryMethod)

//    Logger.getLogger("org").setLevel(Level.ERROR)
//
//    // This is needed for RDD operations
//    val conf = new SparkConf().setAppName(APP_NAME).setMaster(MASTER)
//    val sc = new SparkContext(conf)
//
//    // This is needed for Dataframe or Dataset operations
//    val spark = SparkSession.builder
//      .appName(APP_NAME)
//      .master(MASTER)
//      .getOrCreate()
//
//    val task:SparkTask = new DomesticAirlineOnTimePerformanceDF(spark, AIRLINE_CSV_FILE);

    assert(1===1)
  }
}
